### ISSUE TITLE
Seek issues with multi-channel mp3s

### ISSUE THREAD

**Issue by LordAro** [UniversityRadioYork/ury-playd#106]
Steps to reproduce:
1. load file
2. play til finished
3. seek back 5 seconds
4. try to play*
5. seek back to 5s (absolute)
6. play
7. watch as file apparently ends 5s early, despite getting to end of file

*it doesn't, goes to playing then flicks back to finished on the next Audio::Update, apparently due to a lack of samples in the buffer or something?

Mono-channel mp3s are fine

**Comment by CaptainHayashi** [comment]
This seems to be an off-by-factor-of-`ChannelCount` error, yay!  Am about to push a prq with a possible fix.
