### ISSUE TITLE
Strange include in CMake CFLAGS

### ISSUE THREAD

**Issue by DinCahill** [UniversityRadioYork/ury-playd#119]
/usr/bin/c++   -DPD_VERSION=\"v0.3.0-65-gb9b8635\" -DWITH_MP3 -DWITH_SNDFILE **-I/home/vagrant/ury-playd/playd** -I/usr/include/SDL2 **-I/home/vagrant/ury-playd/playd_tests**  -std=c++14   -o CMakeFiles/playd.dir/src/main.cpp.o -c /home/vagrant/ury-playd/src/main.cpp

I'm not sure where these are coming from. If you run cmake from outside of the git root, the includes are benign, but if you run it inside, those paths are the output paths of the `playd` and `playd_tests` binaries. This generates annoying warnings if either exists:

`cc1plus: warning: /home/vagrant/ury-playd/playd: not a directory`

**Comment by LordAro** [comment]
I'm not seeing this myself:

```
/usr/bin/c++   -DPD_VERSION=\"v0.3.0-102-g68a37c1\" -DWITH_MP3 -DWITH_SNDFILE -I/home/lordaro/dev/ury-playd/playd -I/usr/include/SDL2 -I/home/lordaro/dev/ury-playd/playd_tests  -std=c++14   -o CMakeFiles/playd.dir/src/audio/sources/mp3.cpp.o -c /home/lordaro/dev/ury-playd/src/audio/sources/mp3.cpp
```

Something to do with your environment PATH, perhaps?

**Comment by DinCahill** [comment]
/usr/bin/c++   -DPD_VERSION=\"v0.3.0-102-g68a37c1\" -DWITH_MP3 -DWITH_SNDFILE **-I/home/lordaro/dev/ury-playd/playd** -I/usr/include/SDL2 **-I/home/lordaro/dev/ury-playd/playd_tests**  -std=c++14   -o CMakeFiles/playd.dir/src/audio/sources/mp3.cpp.o -c /home/lordaro/dev/ury-playd/src/audio/sources/mp3.cpp

wot

**Comment by DinCahill** [comment]
Ah, I'm using `include_directories` like it were `target_include_directories`. I'll bundle up the fix with some other CMake stuff later.
