### ISSUE TITLE
Erroneous escaping in load error

### ISSUE THREAD

**Issue by wlcx** [UniversityRadioYork/ury-playd#79]
Seems to be some erroneous escaping going on.
```
[readers.c:1182] error: Cannot open file /home/roger/musiclibrary/Steely Dan/Gaucho/01 Gaucho.mp3: No such file or directory
DEBUG: Sending command: STATE Ejected
DEBUG: Sending command: FAIL 'mp3: can'\''t open /home/roger/musiclibrary/Steely Dan/Gaucho/01 Gaucho.mp3: File access error. (code 22)' load '/home/roger/musiclibrary/Steely Dan/Gaucho/01 Gaucho.mp3'
```
On the client end I get:
```
STATE ejected
FAIL 'mp3: can'\''t open /home/roger/musiclibrary/Steely Dan/Gaucho/01 Gaucho.mp3: File access error. (code 22)' load '/home/roger/musiclibrary/Steely Dan/Gaucho/01 Gaucho.mp3'
```

**Comment by CaptainHayashi** [comment]
The `'\''` looks like the correct thing to do in that situation (that's how you'd have a `'` inside `''` quotes), but really the error message shouldn't have a `'` in it (should be 'opening BLAH failed' or 'cannot open BLAH').  All the other quoting looks fine there--the load should be out of quotes and the path in quotes as the 2nd and subsequent arguments of a `FAIL` are the original command.

**Comment by wlcx** [comment]
Forgot this wasn't supposed to be 'human readable' Derp.
