### ISSUE TITLE
[Linux, Pulseaudio] crash on subsequent load

### ISSUE THREAD

**Issue by wlcx** [UniversityRadioYork/ury-playd#81]
After a LOAD, any subsequent LOAD crashes playd as seen below. Arch Linux, Pulseaudio
Reproduced in mp3, wav and flac, not reproducable on OSX or Freebsd using OSS (cc @adfw). Seems likely to be a pulse thang.

```
DEBUG: Sending command: FILE '/home/roger/musiclibrary/Steely Dan/Gaucho/05 Time Out Of Mind.mp3'
DEBUG: Sending command: TIME 0
DEBUG: Sending command: STATE Stopped
DEBUG: Sending command: OK load '/home/roger/musiclibrary/Steely Dan/Gaucho/05 Time Out Of Mind.mp3'
DEBUG: Received command: "eject"
DEBUG: Sending command: STATE Ejected
DEBUG: Sending command: OK eject
DEBUG: Received command: "load" "/home/roger/musiclibrary/Steely Dan/Gaucho/05 Time Out Of Mind.mp3"
DEBUG: trying to enable formats at  8000
DEBUG: trying to enable formats at  11025
DEBUG: trying to enable formats at  12000
DEBUG: trying to enable formats at  16000
DEBUG: trying to enable formats at  22050
DEBUG: trying to enable formats at  24000
DEBUG: trying to enable formats at  32000
DEBUG: trying to enable formats at  44100
DEBUG: trying to enable formats at  48000
DEBUG: Sending command: STATE Ejected
Unhandled exception in main loop: couldn't open device: Audio device already open
```

**Comment by LordAro** [comment]
confirmed

**Comment by LordAro** [comment]
The issue is that SdlAudioSink is being constructed each time a track is loaded, which obviously blows up when it tried to open the previously used device
@CaptainHayashi

**Comment by CaptainHayashi** [comment]
Can't reproduce on Windows.  Assuming SDL's pulseaudio backend is much less lenient at holding more than one reference to the same device than other backends.

**Comment by wlcx** [comment]
@adfw reports no issues with OSS + flacs/oggs, which still crash for me with PulseAudio.

**Comment by CaptainHayashi** [comment]
Turns out that, because I hadn't declared the destructors for `Audio` and `AudioSink` virtual, sacrificed 100 llamas to the god of the sun, and danced around the campus lake 20 times while wearing only a feathery headdress, __the destructor for `SdlAudioSink` wasn't being called at all!__

Thanks, Bjarne
