### ISSUE TITLE
Release v0.3.0 already

### ISSUE THREAD

**Issue by CaptainHayashi** [UniversityRadioYork/ury-playd#95]
The number of commits since the last release is staggering (over 150 last time I checked).  We probably want to make a release soonish.

* [ ] Figure out what we're doing with the MSVC build notes
* [ ] Clean up all other issues for v0.3.0
* [ ] Formatting pass
* [ ] cppcheck pass
* [ ] possibly a clang -Weverything pass, for good measure

**Comment by LordAro** [comment]
Number of commits isn't relevant to whether it's time for a release, but as the audio backend's been rewritten, you're probably right
